---

  - name: Download WordPress  
    get_url: 
      url: https://wordpress.org/latest.tar.gz 
      dest: /tmp/wordpress.tar.gz
      validate_certs: no 
  
  - name: Extract WordPress  
    unarchive: 
      src: /tmp/wordpress.tar.gz 
      dest: /var/www/ 
      copy: no 
  
  - name: Update default Apache site
    lineinfile: 
      dest: /etc/apache2/sites-enabled/000-default.conf 
      regexp: "(.)+DocumentRoot /var/www/html"
      line: "DocumentRoot /var/www/wordpress"
    notify:
      - restart apache.  