---

  - name: Create an EC2 instance
    ec2:
      key_name: "{{ project_name }}-{{ env }}-key"
      region: "{{ aws_region }}"
      group_id: "{{ firewall.group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: yes
      instance_tags:
        env: "{{ env }}"
        name: ansible.crafted
        count_tag: env
        exact_count: 1
    register: ec2  