apiVersion: v1
kind: ReplicationController
metadata:
  name: foodtrucks-web
  labels:
    name: foodtrucks-web
    app: foodtrucks
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: foodtrucks-web
          image: prakhar1989/foodtrucks-web
          ports:
            - containerPort: 5000         
              name: http
              protocol: TCP