apiVersion: v1
kind: Service
metadata:
  name: foodtrucks-web
  labels:
    name: foodtrucks-web
    app: foodtrucks
spec:
  selector:
    name: foodtrucks-web
  type: NodePort
  ports:
   - port: 6000
     targetPort: 5000
     protocol: TCP