apiVersion: v1
kind: Service
metadata:
  name: pd2jira
  labels:
    name: pd2jira
    app: pd2jira
spec:
  selector:
    name: pd2jira
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP